// Simple app config that doesn't require tsx
const config = {
  name: "BuildKI",
  slug: "protokoll-app",
  owner: "iserlohs-team",
  version: "1.1.5",
  orientation: "portrait",
  icon: "./assets/images/icon.png",
  scheme: "manus20250614001800",
  userInterfaceStyle: "automatic",
  ios: {
    supportsTablet: true,
    bundleIdentifier: "space.manus.protokoll.app.t20250614001800",
    backgroundColor: "#0B1622",
    associatedDomains: ["applinks:buildki.app"],
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
      NSCameraUsageDescription: "BuildKI verwendet die Kamera nur nach Ihrer Auswahl, um Baustellen-, Projekt- und Mängelfotos sowie Videos aufzunehmen und zuzuordnen.",
      NSMicrophoneUsageDescription: "BuildKI verwendet das Mikrofon nur während einer von Ihnen gestarteten Aufnahme, um Baustellenprotokolle und Sprachnotizen aufzuzeichnen und auf Ihre Anforderung zu transkribieren.",
      NSPhotoLibraryUsageDescription: "BuildKI verwendet ausschließlich die von Ihnen ausgewählten Fotos und Videos für Projekt- und Mängeldokumentation sowie eine von Ihnen gestartete Analyse.",
      NSLocationWhenInUseUsageDescription: "BuildKI verwendet Ihren Standort nur bei aktivierter Standortfreigabe während der App-Nutzung, um Ort und lokales Wetter einem Protokoll oder Bautagebuch zuzuordnen.",
      NSCalendarsUsageDescription: "BuildKI verwendet Ihren Kalender nach Ihrer Auswahl, um bestehende Termine für die Planung zu lesen sowie Protokoll- und Nachprüfungstermine zu erstellen oder zu aktualisieren.",
      NSCalendarsFullAccessUsageDescription: "BuildKI verwendet Ihren Kalender nach Ihrer Auswahl, um bestehende Termine für die Planung zu lesen sowie Protokoll- und Nachprüfungstermine zu erstellen oder zu aktualisieren.",
      NSContactsUsageDescription: "BuildKI verwendet Ihre Kontakte nach Ihrer Auswahl, damit Sie Namen, E-Mail-Adressen und Telefonnummern als Projektbeteiligte oder Empfänger übernehmen können.",
      NSFaceIDUsageDescription: "BuildKI verwendet Face ID ausschließlich auf Ihrem Gerät, um die optionale App-Sperre zu entsperren.",
      NSMotionUsageDescription: "BuildKI nutzt die Bewegungssensoren während einer Aufnahme, um die Geräteausrichtung zu erkennen und Ihre Foto- und Videodokumentation korrekt orientiert zu speichern.",
      UIViewControllerBasedStatusBarAppearance: true,
    },
    privacyManifests: {
      NSPrivacyTracking: false,
      NSPrivacyTrackingDomains: [],
      NSPrivacyCollectedDataTypes: [
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypeName",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypeEmailAddress",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypePhoneNumber",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypePhysicalAddress",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypePreciseLocation",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypePhotosorVideos",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypeAudioData",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypeCustomerSupport",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypeOtherUserContent",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
        {
          NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypeUserID",
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: ["NSPrivacyCollectedDataTypePurposeAppFunctionality"],
        },
      ],
      NSPrivacyAccessedAPITypes: [
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryFileTimestamp",
          NSPrivacyAccessedAPITypeReasons: ["C617.1", "3B52.1"],
        },
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryUserDefaults",
          NSPrivacyAccessedAPITypeReasons: ["CA92.1"],
        },
      ],
    },
  },
  android: {
    adaptiveIcon: {
      backgroundColor: "#0B1622",
      foregroundImage: "./assets/images/android-icon-foreground.png",
      backgroundImage: "./assets/images/android-icon-background.png",
      monochromeImage: "./assets/images/android-icon-monochrome.png",
    },
    edgeToEdgeEnabled: true,
    predictiveBackGestureEnabled: false,
    package: "space.manus.protokoll.app.t20250614001800",
    permissions: ["POST_NOTIFICATIONS", "CAMERA", "RECORD_AUDIO"],
    intentFilters: [
      {
        action: "VIEW",
        autoVerify: true,
        data: [{ scheme: "manus20250614001800", host: "*" }],
        category: ["BROWSABLE", "DEFAULT"],
      },
      {
        action: "VIEW",
        autoVerify: true,
        data: [{ scheme: "https", host: "buildki.app", pathPrefix: "/join" }],
        category: ["BROWSABLE", "DEFAULT"],
      },
    ],
  },
  web: {
    bundler: "metro",
    output: "static",
    favicon: "./assets/images/favicon.png",
  },
  plugins: [
    "expo-asset",
    "expo-font",
    "expo-image",
    "expo-localization",
    "expo-mail-composer",
    "expo-secure-store",
    "expo-sharing",
    "expo-status-bar",
    "expo-web-browser",
    "expo-router",
    ["expo-audio", {
      microphonePermission: "BuildKI verwendet das Mikrofon nur während einer von Ihnen gestarteten Aufnahme, um Baustellenprotokolle und Sprachnotizen aufzuzeichnen und auf Ihre Anforderung zu transkribieren.",
      enableBackgroundRecording: false,
      enableBackgroundPlayback: false,
    }],
    ["expo-video", { supportsBackgroundPlayback: false, supportsPictureInPicture: false }],
    ["expo-splash-screen", {
      image: "./assets/images/splash-icon.png",
      imageWidth: 200,
      resizeMode: "contain",
      backgroundColor: "#0B1622",
      dark: { backgroundColor: "#000000" },
    }],
    ["expo-build-properties", {
      android: { buildArchs: ["armeabi-v7a", "arm64-v8a"], minSdkVersion: 24 },
    }],
    ["expo-camera", { cameraPermission: "BuildKI verwendet die Kamera nur nach Ihrer Auswahl, um Baustellen-, Projekt- und Mängelfotos sowie Videos aufzunehmen und zuzuordnen." }],
    ["expo-location", {
      locationWhenInUsePermission: "BuildKI verwendet Ihren Standort nur bei aktivierter Standortfreigabe während der App-Nutzung, um Ort und lokales Wetter einem Protokoll oder Bautagebuch zuzuordnen.",
      motionUsagePermission: "BuildKI nutzt die Bewegungssensoren während einer Aufnahme, um die Geräteausrichtung zu erkennen und Ihre Foto- und Videodokumentation korrekt orientiert zu speichern.",
      locationAlwaysAndWhenInUsePermission: false,
      locationAlwaysPermission: false,
      isIosBackgroundLocationEnabled: false,
      isAndroidBackgroundLocationEnabled: false,
      isAndroidForegroundServiceEnabled: false,
    }],
    ["expo-calendar", {
      calendarPermission: "BuildKI verwendet Ihren Kalender nach Ihrer Auswahl, um bestehende Termine für die Planung zu lesen sowie Protokoll- und Nachprüfungstermine zu erstellen oder zu aktualisieren.",
      remindersPermission: false,
    }],
    ["expo-contacts", { contactsPermission: "BuildKI verwendet Ihre Kontakte nach Ihrer Auswahl, damit Sie Namen, E-Mail-Adressen und Telefonnummern als Projektbeteiligte oder Empfänger übernehmen können." }],
    ["expo-local-authentication", { faceIDPermission: "BuildKI verwendet Face ID ausschließlich auf Ihrem Gerät, um die optionale App-Sperre zu entsperren." }],
    ["expo-image-picker", {
      photosPermission: "BuildKI verwendet ausschließlich die von Ihnen ausgewählten Fotos und Videos für Projekt- und Mängeldokumentation sowie eine von Ihnen gestartete Analyse.",
      cameraPermission: "BuildKI verwendet die Kamera nur nach Ihrer Auswahl, um Baustellen-, Projekt- und Mängelfotos sowie Videos aufzunehmen und zuzuordnen.",
      microphonePermission: "BuildKI verwendet das Mikrofon nur während einer von Ihnen gestarteten Videoaufnahme.",
    }],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    eas: {
      projectId: "1928b42a-1649-4093-95f5-12060d8da8c5",
    },
  },
};

module.exports = config;
