CREATE TABLE `attachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`entityType` varchar(32) NOT NULL,
	`entityLocalId` varchar(64) NOT NULL,
	`storageKey` varchar(512) NOT NULL,
	`storageUrl` varchar(512) NOT NULL,
	`originalName` varchar(255),
	`mimeType` varchar(128),
	`sizeBytes` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `attachments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`localId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`projectId` varchar(64) NOT NULL,
	`date` varchar(10) NOT NULL,
	`weather` text,
	`attendance` text,
	`defectsSummary` text,
	`activities` text,
	`notes` text,
	`generatedReport` text,
	`photos` text,
	`status` varchar(32) DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `defects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`localId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`projectId` varchar(64) NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`status` varchar(32) NOT NULL DEFAULT 'offen',
	`priority` varchar(16) NOT NULL DEFAULT 'mittel',
	`category` varchar(64),
	`gewerk` varchar(64),
	`photos` text,
	`beforePhotos` text,
	`afterPhotos` text,
	`assignee` varchar(128),
	`assigneeFirma` varchar(128),
	`dueDate` varchar(32),
	`location` varchar(255),
	`floor` varchar(64),
	`room` varchar(128),
	`positionCode` varchar(32),
	`followUpDate` varchar(32),
	`followUpResult` varchar(32),
	`source` varchar(32),
	`confidence` int,
	`protocolId` varchar(64),
	`analysisId` varchar(64),
	`matterportModelId` varchar(128),
	`matterportPosition` text,
	`matterportNormal` text,
	`matterportSweepId` varchar(128),
	`matterportFloorIndex` int,
	`matterportFloorName` varchar(128),
	`matterportRoomId` varchar(128),
	`matterportRoomName` varchar(128),
	`aiSummary` text,
	`voiceNoteUri` text,
	`signatures` text,
	`comments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`resolvedAt` timestamp,
	CONSTRAINT `defects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`localId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`prefix` varchar(16),
	`color` varchar(32),
	`address` text,
	`client` varchar(255),
	`status` varchar(32) DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
