import { useState, useCallback } from "react";
import {
  View,
  Text,
  FlatList,
  Pressable,
  StyleSheet,
  Modal,
  TextInput,
  ScrollView,
  Alert,
  Keyboard,
  KeyboardAvoidingView,
  InputAccessoryView,
  Platform,
} from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useRouter, useLocalSearchParams, useFocusEffect } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Haptics from "expo-haptics";
import { useTranslation } from "@/lib/language-provider";
import { TradePicker } from "@/components/trade-picker";
import {
  DiaryEntry,
  getDiaryEntries,
  saveDiaryEntry,
  deleteDiaryEntry,
} from "@/lib/diary-store";

const DIARY_INPUT_ACCESSORY_ID = "diary-input-accessory";

export default function DiaryScreen() {
  const { t } = useTranslation();
  const colors = useColors();
  const router = useRouter();
  const params = useLocalSearchParams<{ projectId?: string }>();
  const projectId = params.projectId || "";

  const [entries, setEntries] = useState<DiaryEntry[]>([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [selectedEntry, setSelectedEntry] = useState<DiaryEntry | null>(null);

  // Form state
  const [workers, setWorkers] = useState("");
  const [workFrom, setWorkFrom] = useState("07:00");
  const [workTo, setWorkTo] = useState("16:00");
  const [selectedTrades, setSelectedTrades] = useState<string[]>([]);
  const [tradeToAdd, setTradeToAdd] = useState("");
  const [activities, setActivities] = useState("");
  const [deliveries, setDeliveries] = useState("");
  const [incidents, setIncidents] = useState("");
  const [notes, setNotes] = useState("");

  useFocusEffect(
    useCallback(() => {
      loadEntries();
    }, [projectId])
  );

  async function loadEntries() {
    const loaded = await getDiaryEntries(projectId || undefined);
    setEntries(loaded);
  }

  const today = new Date().toISOString().split("T")[0];

  const createEntry = async () => {
    Keyboard.dismiss();
    const entry: DiaryEntry = {
      id: `diary-${projectId}-${today}-${Date.now()}`,
      projectId,
      date: today,
      workersOnSite: workers ? parseInt(workers) : undefined,
      workHours: { from: workFrom, to: workTo },
      trades: [...selectedTrades],
      activities: activities.split("\n").map((activity) => activity.trim()).filter(Boolean),
      deliveries: deliveries.split("\n").filter((d) => d.trim()),
      incidents: incidents.split("\n").filter((i) => i.trim()),
      notes: notes.trim(),
      protocolIds: [],
      photos: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      autoGenerated: false,
    };

    await saveDiaryEntry(entry);
    await loadEntries();
    setShowCreateModal(false);
    resetForm();
    if (Platform.OS !== "web") Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
  };

  const resetForm = () => {
    setWorkers("");
    setWorkFrom("07:00");
    setWorkTo("16:00");
    setSelectedTrades([]);
    setTradeToAdd("");
    setActivities("");
    setDeliveries("");
    setIncidents("");
    setNotes("");
  };

  const addSelectedTrade = (trade: string) => {
    setTradeToAdd("");
    Keyboard.dismiss();
    if (!trade) return;
    setSelectedTrades((current) => current.includes(trade) ? current : [...current, trade]);
  };

  const removeSelectedTrade = (trade: string) => {
    setSelectedTrades((current) => current.filter((item) => item !== trade));
  };

  const removeEntry = (entryId: string) => {
    Alert.alert(t('alert_eintrag_loeschen'), t('msg_diesen_tagebucheintrag_wirklich_entfernen'), [
      { text: t('btn_abbrechen'), style: "cancel" },
      {
        text: t('btn_loeschen'),
        style: "destructive",
        onPress: async () => {
          await deleteDiaryEntry(entryId);
          await loadEntries();
        },
      },
    ]);
  };

  const formatDate = (dateStr: string): string => {
    const d = new Date(dateStr + "T00:00:00");
    const days = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"];
    return `${days[d.getDay()]}, ${d.getDate()}.${d.getMonth() + 1}.${d.getFullYear()}`;
  };

  const renderEntry = ({ item }: { item: DiaryEntry }) => (
    <Pressable
      onPress={() => setSelectedEntry(item)}
      onLongPress={() => removeEntry(item.id)}
      style={({ pressed }) => [
        styles.entryCard,
        { backgroundColor: colors.surface, borderColor: colors.border },
        pressed && { opacity: 0.7 },
      ]}
    >
      <View style={styles.entryHeader}>
        <View style={styles.dateContainer}>
          <MaterialIcons name="calendar-today" size={16} color={colors.primary} />
          <Text style={[styles.entryDate, { color: colors.foreground }]}>{formatDate(item.date)}</Text>
        </View>
        {item.autoGenerated && (
          <View style={[styles.autoBadge, { backgroundColor: colors.primary + "20" }]}>
            <Text style={[styles.autoBadgeText, { color: colors.primary }]}>{t('auto')}</Text>
          </View>
        )}
      </View>

      {item.weather && (
        <Text style={[styles.weatherText, { color: colors.muted }]}>
          {item.weather.description}, {item.weather.temperature}°C
        </Text>
      )}

      <View style={styles.entryStats}>
        {item.workersOnSite != null && (
          <View style={styles.entryStat}>
            <MaterialIcons name="people" size={14} color={colors.muted} />
            <Text style={[styles.entryStatText, { color: colors.muted }]}>{item.workersOnSite}</Text>
          </View>
        )}
        {item.workHours && (
          <View style={styles.entryStat}>
            <MaterialIcons name="schedule" size={14} color={colors.muted} />
            <Text style={[styles.entryStatText, { color: colors.muted }]}>{item.workHours.from}–{item.workHours.to}</Text>
          </View>
        )}
        <View style={styles.entryStat}>
          <MaterialIcons name="list" size={14} color={colors.muted} />
          <Text style={[styles.entryStatText, { color: colors.muted }]}>{item.trades?.length || item.activities.length} Gewerke</Text>
        </View>
      </View>

      {((item.trades?.length || 0) > 0 || item.activities.length > 0) && (
        <Text style={[styles.activityPreview, { color: colors.foreground }]} numberOfLines={2}>
          {[...(item.trades || []), ...item.activities].slice(0, 3).join(" • ")}
        </Text>
      )}
    </Pressable>
  );

  return (
    <ScreenContainer className="p-4">
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backBtn, pressed && { opacity: 0.7 }]}>
          <MaterialIcons name="arrow-back" size={24} color={colors.foreground} />
        </Pressable>
        <Text style={[styles.title, { color: colors.foreground }]}>{t('bautagebuch')}</Text>
        <Pressable onPress={() => setShowCreateModal(true)} style={({ pressed }) => [styles.addBtn, pressed && { opacity: 0.7 }]}>
          <MaterialIcons name="add" size={24} color={colors.primary} />
        </Pressable>
      </View>

      {/* Summary */}
      <View style={[styles.summaryCard, { backgroundColor: colors.primary + "10", borderColor: colors.primary + "30" }]}>
        <MaterialIcons name="auto-stories" size={24} color={colors.primary} />
        <View style={styles.summaryText}>
          <Text style={[styles.summaryTitle, { color: colors.foreground }]}>{entries.length} Einträge</Text>
          <Text style={[styles.summarySubtitle, { color: colors.muted }]}>
            {entries.length > 0 ? t('letzter_eintrag').replace('{date}', formatDate(entries[0]?.date)) : t('noch_keine_eintraege')}
          </Text>
        </View>
      </View>

      {/* Entry List */}
      <FlatList
        data={entries}
        keyExtractor={(item) => item.id}
        renderItem={renderEntry}
        contentContainerStyle={styles.list}
        ListEmptyComponent={
          <View style={styles.emptyState}>
            <MaterialIcons name="menu-book" size={48} color={colors.muted} />
            <Text style={[styles.emptyText, { color: colors.muted }]}>{t('noch_keine_eintraege')}</Text>
            <Text style={[styles.emptySubtext, { color: colors.muted }]}>
              Erstelle tägliche Bautagebuch-Einträge oder lass sie automatisch aus Protokollen generieren
            </Text>
          </View>
        }
      />

      {/* Detail Modal */}
      <Modal visible={!!selectedEntry} transparent animationType="slide">
        <View style={styles.modalOverlay}>
          <View style={[styles.modalContent, { backgroundColor: colors.surface }]}>
            <ScrollView>
              {selectedEntry && (
                <>
                  <Text style={[styles.modalTitle, { color: colors.foreground }]}>
                    {formatDate(selectedEntry.date)}
                  </Text>

                  {selectedEntry.weather && (
                    <Text style={[styles.detailSection, { color: colors.muted }]}>
                      Wetter: {selectedEntry.weather.description}, {selectedEntry.weather.temperature}°C
                    </Text>
                  )}

                  {selectedEntry.workersOnSite != null && (
                    <Text style={[styles.detailSection, { color: colors.muted }]}>
                      Arbeiter vor Ort: {selectedEntry.workersOnSite}
                    </Text>
                  )}

                  {selectedEntry.workHours && (
                    <Text style={[styles.detailSection, { color: colors.muted }]}>
                      Arbeitszeit: {selectedEntry.workHours.from} – {selectedEntry.workHours.to}
                    </Text>
                  )}

                  {selectedEntry.trades && selectedEntry.trades.length > 0 && (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>Gewerke</Text>
                      {selectedEntry.trades.map((trade) => (
                        <Text key={trade} style={[styles.detailItem, { color: colors.muted }]}>• {trade}</Text>
                      ))}
                    </View>
                  )}

                  {selectedEntry.activities.length > 0 && (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>Tätigkeitsdetails</Text>
                      {selectedEntry.activities.map((a, i) => (
                        <Text key={i} style={[styles.detailItem, { color: colors.muted }]}>• {a}</Text>
                      ))}
                    </View>
                  )}

                  {selectedEntry.deliveries.length > 0 && (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>{t('lieferungen')}</Text>
                      {selectedEntry.deliveries.map((d, i) => (
                        <Text key={i} style={[styles.detailItem, { color: colors.muted }]}>• {d}</Text>
                      ))}
                    </View>
                  )}

                  {selectedEntry.incidents.length > 0 && (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>{t('vorkommnisse')}</Text>
                      {selectedEntry.incidents.map((inc, i) => (
                        <Text key={i} style={[styles.detailItem, { color: colors.muted }]}>• {inc}</Text>
                      ))}
                    </View>
                  )}

                  {selectedEntry.notes ? (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>{t('bemerkungen')}</Text>
                      <Text style={[styles.detailItem, { color: colors.muted }]}>{selectedEntry.notes}</Text>
                    </View>
                  ) : null}
                </>
              )}
            </ScrollView>
            <Pressable
              onPress={() => setSelectedEntry(null)}
              style={({ pressed }) => [styles.closeBtn, { backgroundColor: colors.primary }, pressed && { opacity: 0.8 }]}
            >
              <Text style={styles.closeBtnText}>{t('close')}</Text>
            </Pressable>
          </View>
        </View>
      </Modal>

      {/* Create Modal */}
      <Modal visible={showCreateModal} transparent animationType="slide">
        <KeyboardAvoidingView
          style={styles.modalOverlay}
          behavior={Platform.OS === "ios" ? "padding" : "height"}
          keyboardVerticalOffset={Platform.OS === "ios" ? 12 : 0}
        >
          <View style={[styles.modalContent, { backgroundColor: colors.surface }]}>
            <ScrollView
              style={styles.createScroll}
              contentContainerStyle={styles.createScrollContent}
              keyboardShouldPersistTaps="handled"
              keyboardDismissMode={Platform.OS === "ios" ? "interactive" : "on-drag"}
              onScrollBeginDrag={Keyboard.dismiss}
              showsVerticalScrollIndicator
            >
            <Text style={[styles.modalTitle, { color: colors.foreground }]}>{t('neuer_tagebucheintrag')}</Text>
            <Text style={[styles.modalSubtitle, { color: colors.muted }]}>{formatDate(today)}</Text>

            <View style={styles.formRow}>
              <View style={styles.formHalf}>
                <Text style={[styles.formLabel, { color: colors.muted }]}>{t('arbeiter')}</Text>
                <TextInput
                  style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
                  placeholder={t('anzahl')}
                  placeholderTextColor={colors.muted}
                  value={workers}
                  onChangeText={setWorkers}
                  keyboardType="numeric"
                  returnKeyType="done"
                  onSubmitEditing={Keyboard.dismiss}
                  inputAccessoryViewID={Platform.OS === "ios" ? DIARY_INPUT_ACCESSORY_ID : undefined}
                />
              </View>
              <View style={styles.formHalf}>
                <Text style={[styles.formLabel, { color: colors.muted }]}>{t('arbeitszeit')}</Text>
                <View style={styles.timeRow}>
                  <TextInput
                    style={[styles.timeInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
                    value={workFrom}
                    onChangeText={setWorkFrom}
                    placeholder="07:00"
                    placeholderTextColor={colors.muted}
                    returnKeyType="done"
                    onSubmitEditing={Keyboard.dismiss}
                    inputAccessoryViewID={Platform.OS === "ios" ? DIARY_INPUT_ACCESSORY_ID : undefined}
                  />
                  <Text style={[{ color: colors.muted }]}>–</Text>
                  <TextInput
                    style={[styles.timeInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
                    value={workTo}
                    onChangeText={setWorkTo}
                    placeholder="16:00"
                    placeholderTextColor={colors.muted}
                    returnKeyType="done"
                    onSubmitEditing={Keyboard.dismiss}
                    inputAccessoryViewID={Platform.OS === "ios" ? DIARY_INPUT_ACCESSORY_ID : undefined}
                  />
                </View>
              </View>
            </View>

            <Text style={[styles.formLabel, { color: colors.muted }]}>Gewerke</Text>
            <TradePicker
              value={tradeToAdd}
              onChange={addSelectedTrade}
              placeholder="Gewerk hinzufügen"
              allowEmpty={false}
              accessibilityLabel="Gewerk zum Tagebuch hinzufügen"
            />
            {selectedTrades.length > 0 && (
              <FlatList
                horizontal
                data={selectedTrades}
                keyExtractor={(item) => item}
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={styles.selectedTrades}
                renderItem={({ item }) => (
                  <Pressable
                    onPress={() => removeSelectedTrade(item)}
                    accessibilityRole="button"
                    accessibilityLabel={`${item} entfernen`}
                    style={[styles.selectedTradeChip, { borderColor: colors.primary, backgroundColor: colors.primary + "12" }]}
                  >
                    <Text style={[styles.selectedTradeText, { color: colors.primary }]}>{item}</Text>
                    <MaterialIcons name="close" size={16} color={colors.primary} />
                  </Pressable>
                )}
              />
            )}

            <Text style={[styles.formLabel, { color: colors.muted }]}>Tätigkeitsdetails (optional, eine pro Zeile)</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder="z.B. Obergeschoss nivelliert"
              placeholderTextColor={colors.muted}
              value={activities}
              onChangeText={setActivities}
              multiline
              numberOfLines={3}
              inputAccessoryViewID={Platform.OS === "ios" ? DIARY_INPUT_ACCESSORY_ID : undefined}
            />

            <Text style={[styles.formLabel, { color: colors.muted }]}>{t('lieferungen_eine_pro_zeile')}</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder="z.B. 5m³ Beton&#10;Fenster Lieferung"
              placeholderTextColor={colors.muted}
              value={deliveries}
              onChangeText={setDeliveries}
              multiline
              numberOfLines={3}
              inputAccessoryViewID={Platform.OS === "ios" ? DIARY_INPUT_ACCESSORY_ID : undefined}
            />

            <Text style={[styles.formLabel, { color: colors.muted }]}>{t('vorkommnisse')}</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder="z.B. Wasserrohrbruch Keller"
              placeholderTextColor={colors.muted}
              value={incidents}
              onChangeText={setIncidents}
              multiline
              numberOfLines={2}
              inputAccessoryViewID={Platform.OS === "ios" ? DIARY_INPUT_ACCESSORY_ID : undefined}
            />

            <Text style={[styles.formLabel, { color: colors.muted }]}>{t('bemerkungen')}</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder={t('sonstige_anmerkungen')}
              placeholderTextColor={colors.muted}
              value={notes}
              onChangeText={setNotes}
              multiline
              numberOfLines={2}
              inputAccessoryViewID={Platform.OS === "ios" ? DIARY_INPUT_ACCESSORY_ID : undefined}
            />

            <View style={styles.modalButtons}>
              <Pressable
                onPress={() => { Keyboard.dismiss(); setShowCreateModal(false); resetForm(); }}
                style={({ pressed }) => [styles.cancelBtn, { borderColor: colors.border }, pressed && { opacity: 0.7 }]}
              >
                <Text style={[styles.cancelBtnText, { color: colors.muted }]}>{t('cancel')}</Text>
              </Pressable>
              <Pressable
                onPress={createEntry}
                style={({ pressed }) => [styles.saveBtn, { backgroundColor: colors.primary }, pressed && { opacity: 0.8 }]}
              >
                <Text style={styles.saveBtnText}>{t('save')}</Text>
              </Pressable>
            </View>
            </ScrollView>
          </View>
        </KeyboardAvoidingView>
      </Modal>

      {Platform.OS === "ios" && (
        <InputAccessoryView nativeID={DIARY_INPUT_ACCESSORY_ID}>
          <View style={[styles.keyboardAccessory, { backgroundColor: colors.surface, borderColor: colors.border }]}>
            <Pressable onPress={Keyboard.dismiss} accessibilityRole="button" accessibilityLabel="Tastatur schließen" style={styles.keyboardDoneButton}>
              <Text style={[styles.keyboardDoneText, { color: colors.primary }]}>Fertig</Text>
            </Pressable>
          </View>
        </InputAccessoryView>
      )}
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  header: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  backBtn: { padding: 8, marginRight: 8 },
  title: { fontSize: 22, fontWeight: "700", flex: 1 },
  addBtn: { padding: 8 },
  summaryCard: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderRadius: 0, borderWidth: 1, marginBottom: 16 },
  summaryText: { flex: 1 },
  summaryTitle: { fontSize: 16, fontWeight: "600" },
  summarySubtitle: { fontSize: 13, marginTop: 2 },
  list: { paddingBottom: 20 },
  entryCard: { padding: 14, borderRadius: 0, borderWidth: 1, marginBottom: 8 },
  entryHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  dateContainer: { flexDirection: "row", alignItems: "center", gap: 6 },
  entryDate: { fontSize: 15, fontWeight: "600" },
  autoBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 0 },
  autoBadgeText: { fontSize: 11, fontWeight: "600" },
  weatherText: { fontSize: 13, marginTop: 4 },
  entryStats: { flexDirection: "row", gap: 12, marginTop: 8 },
  entryStat: { flexDirection: "row", alignItems: "center", gap: 4 },
  entryStatText: { fontSize: 12 },
  activityPreview: { fontSize: 13, marginTop: 8 },
  emptyState: { alignItems: "center", paddingTop: 60, gap: 12 },
  emptyText: { fontSize: 16, fontWeight: "500" },
  emptySubtext: { fontSize: 13, textAlign: "center", paddingHorizontal: 32 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  modalContent: { borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, maxHeight: "90%" },
  createScroll: { flexGrow: 0 },
  createScrollContent: { paddingBottom: 56 },
  modalTitle: { fontSize: 18, fontWeight: "700" },
  modalSubtitle: { fontSize: 14, marginTop: 4, marginBottom: 16 },
  detailSection: { fontSize: 14, marginTop: 8 },
  detailBlock: { marginTop: 16 },
  detailLabel: { fontSize: 15, fontWeight: "600", marginBottom: 6 },
  detailItem: { fontSize: 14, marginBottom: 3 },
  closeBtn: { paddingVertical: 14, borderRadius: 0, alignItems: "center", marginTop: 16 },
  closeBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  formRow: { flexDirection: "row", gap: 12, marginBottom: 4 },
  formHalf: { flex: 1 },
  formLabel: { fontSize: 13, fontWeight: "500", marginBottom: 6, marginTop: 8 },
  selectedTrades: { gap: 8, paddingBottom: 4 },
  selectedTradeChip: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderRadius: 0, paddingHorizontal: 12 },
  selectedTradeText: { fontSize: 13, fontWeight: "700" },
  input: { borderWidth: 1, borderRadius: 0, padding: 12, fontSize: 15, marginBottom: 8 },
  textArea: { minHeight: 70, textAlignVertical: "top" },
  timeRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  timeInput: { flex: 1, borderWidth: 1, borderRadius: 0, padding: 10, fontSize: 14, textAlign: "center" },
  modalButtons: { flexDirection: "row", gap: 12, marginTop: 16 },
  cancelBtn: { flex: 1, paddingVertical: 14, borderRadius: 0, borderWidth: 1, alignItems: "center" },
  cancelBtnText: { fontSize: 15, fontWeight: "600" },
  saveBtn: { flex: 1, paddingVertical: 14, borderRadius: 0, alignItems: "center" },
  saveBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  keyboardAccessory: { minHeight: 44, flexDirection: "row", justifyContent: "flex-end", alignItems: "center", borderTopWidth: 1, paddingHorizontal: 12 },
  keyboardDoneButton: { minWidth: 72, minHeight: 44, alignItems: "center", justifyContent: "center" },
  keyboardDoneText: { fontSize: 16, fontWeight: "800" },
});
