import { useState, useCallback } from "react";
import {
  View,
  Text,
  FlatList,
  Pressable,
  StyleSheet,
  Modal,
  TextInput,
  ScrollView,
  Alert,
} from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useRouter, useLocalSearchParams, useFocusEffect } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Haptics from "expo-haptics";
import { Platform } from "react-native";
import {
  DiaryEntry,
  getDiaryEntries,
  saveDiaryEntry,
  deleteDiaryEntry,
  formatDiaryForExport,
} from "@/lib/diary-store";

export default function DiaryScreen() {
  const colors = useColors();
  const router = useRouter();
  const params = useLocalSearchParams<{ projectId?: string }>();
  const projectId = params.projectId || "";

  const [entries, setEntries] = useState<DiaryEntry[]>([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [selectedEntry, setSelectedEntry] = useState<DiaryEntry | null>(null);

  // Form state
  const [workers, setWorkers] = useState("");
  const [workFrom, setWorkFrom] = useState("07:00");
  const [workTo, setWorkTo] = useState("16:00");
  const [activities, setActivities] = useState("");
  const [deliveries, setDeliveries] = useState("");
  const [incidents, setIncidents] = useState("");
  const [notes, setNotes] = useState("");

  useFocusEffect(
    useCallback(() => {
      loadEntries();
    }, [projectId])
  );

  const loadEntries = async () => {
    const loaded = await getDiaryEntries(projectId || undefined);
    setEntries(loaded);
  };

  const today = new Date().toISOString().split("T")[0];

  const createEntry = async () => {
    const entry: DiaryEntry = {
      id: `diary-${projectId}-${today}-${Date.now()}`,
      projectId,
      date: today,
      workersOnSite: workers ? parseInt(workers) : undefined,
      workHours: { from: workFrom, to: workTo },
      activities: activities.split("\n").filter((a) => a.trim()),
      deliveries: deliveries.split("\n").filter((d) => d.trim()),
      incidents: incidents.split("\n").filter((i) => i.trim()),
      notes: notes.trim(),
      protocolIds: [],
      photos: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      autoGenerated: false,
    };

    await saveDiaryEntry(entry);
    await loadEntries();
    setShowCreateModal(false);
    resetForm();
    if (Platform.OS !== "web") Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
  };

  const resetForm = () => {
    setWorkers("");
    setWorkFrom("07:00");
    setWorkTo("16:00");
    setActivities("");
    setDeliveries("");
    setIncidents("");
    setNotes("");
  };

  const removeEntry = (entryId: string) => {
    Alert.alert("Eintrag löschen", "Diesen Tagebuch-Eintrag wirklich entfernen?", [
      { text: "Abbrechen", style: "cancel" },
      {
        text: "Löschen",
        style: "destructive",
        onPress: async () => {
          await deleteDiaryEntry(entryId);
          await loadEntries();
        },
      },
    ]);
  };

  const formatDate = (dateStr: string): string => {
    const d = new Date(dateStr + "T00:00:00");
    const days = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"];
    return `${days[d.getDay()]}, ${d.getDate()}.${d.getMonth() + 1}.${d.getFullYear()}`;
  };

  const renderEntry = ({ item }: { item: DiaryEntry }) => (
    <Pressable
      onPress={() => setSelectedEntry(item)}
      onLongPress={() => removeEntry(item.id)}
      style={({ pressed }) => [
        styles.entryCard,
        { backgroundColor: colors.surface, borderColor: colors.border },
        pressed && { opacity: 0.7 },
      ]}
    >
      <View style={styles.entryHeader}>
        <View style={styles.dateContainer}>
          <MaterialIcons name="calendar-today" size={16} color={colors.primary} />
          <Text style={[styles.entryDate, { color: colors.foreground }]}>{formatDate(item.date)}</Text>
        </View>
        {item.autoGenerated && (
          <View style={[styles.autoBadge, { backgroundColor: colors.primary + "20" }]}>
            <Text style={[styles.autoBadgeText, { color: colors.primary }]}>Auto</Text>
          </View>
        )}
      </View>

      {item.weather && (
        <Text style={[styles.weatherText, { color: colors.muted }]}>
          {item.weather.description}, {item.weather.temperature}°C
        </Text>
      )}

      <View style={styles.entryStats}>
        {item.workersOnSite != null && (
          <View style={styles.entryStat}>
            <MaterialIcons name="people" size={14} color={colors.muted} />
            <Text style={[styles.entryStatText, { color: colors.muted }]}>{item.workersOnSite}</Text>
          </View>
        )}
        {item.workHours && (
          <View style={styles.entryStat}>
            <MaterialIcons name="schedule" size={14} color={colors.muted} />
            <Text style={[styles.entryStatText, { color: colors.muted }]}>{item.workHours.from}–{item.workHours.to}</Text>
          </View>
        )}
        <View style={styles.entryStat}>
          <MaterialIcons name="list" size={14} color={colors.muted} />
          <Text style={[styles.entryStatText, { color: colors.muted }]}>{item.activities.length} Tätigkeiten</Text>
        </View>
      </View>

      {item.activities.length > 0 && (
        <Text style={[styles.activityPreview, { color: colors.foreground }]} numberOfLines={2}>
          {item.activities.slice(0, 2).join(" • ")}
        </Text>
      )}
    </Pressable>
  );

  return (
    <ScreenContainer className="p-4">
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={({ pressed }) => [styles.backBtn, pressed && { opacity: 0.7 }]}>
          <MaterialIcons name="arrow-back" size={24} color={colors.foreground} />
        </Pressable>
        <Text style={[styles.title, { color: colors.foreground }]}>Bautagebuch</Text>
        <Pressable onPress={() => setShowCreateModal(true)} style={({ pressed }) => [styles.addBtn, pressed && { opacity: 0.7 }]}>
          <MaterialIcons name="add" size={24} color={colors.primary} />
        </Pressable>
      </View>

      {/* Summary */}
      <View style={[styles.summaryCard, { backgroundColor: colors.primary + "10", borderColor: colors.primary + "30" }]}>
        <MaterialIcons name="auto-stories" size={24} color={colors.primary} />
        <View style={styles.summaryText}>
          <Text style={[styles.summaryTitle, { color: colors.foreground }]}>{entries.length} Einträge</Text>
          <Text style={[styles.summarySubtitle, { color: colors.muted }]}>
            {entries.length > 0 ? `Letzter Eintrag: ${formatDate(entries[0]?.date)}` : "Noch keine Einträge"}
          </Text>
        </View>
      </View>

      {/* Entry List */}
      <FlatList
        data={entries}
        keyExtractor={(item) => item.id}
        renderItem={renderEntry}
        contentContainerStyle={styles.list}
        ListEmptyComponent={
          <View style={styles.emptyState}>
            <MaterialIcons name="menu-book" size={48} color={colors.muted} />
            <Text style={[styles.emptyText, { color: colors.muted }]}>Noch keine Einträge</Text>
            <Text style={[styles.emptySubtext, { color: colors.muted }]}>
              Erstelle tägliche Bautagebuch-Einträge oder lass sie automatisch aus Protokollen generieren
            </Text>
          </View>
        }
      />

      {/* Detail Modal */}
      <Modal visible={!!selectedEntry} transparent animationType="slide">
        <View style={styles.modalOverlay}>
          <View style={[styles.modalContent, { backgroundColor: colors.surface }]}>
            <ScrollView>
              {selectedEntry && (
                <>
                  <Text style={[styles.modalTitle, { color: colors.foreground }]}>
                    {formatDate(selectedEntry.date)}
                  </Text>

                  {selectedEntry.weather && (
                    <Text style={[styles.detailSection, { color: colors.muted }]}>
                      Wetter: {selectedEntry.weather.description}, {selectedEntry.weather.temperature}°C
                    </Text>
                  )}

                  {selectedEntry.workersOnSite != null && (
                    <Text style={[styles.detailSection, { color: colors.muted }]}>
                      Arbeiter vor Ort: {selectedEntry.workersOnSite}
                    </Text>
                  )}

                  {selectedEntry.workHours && (
                    <Text style={[styles.detailSection, { color: colors.muted }]}>
                      Arbeitszeit: {selectedEntry.workHours.from} – {selectedEntry.workHours.to}
                    </Text>
                  )}

                  {selectedEntry.activities.length > 0 && (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>Tätigkeiten</Text>
                      {selectedEntry.activities.map((a, i) => (
                        <Text key={i} style={[styles.detailItem, { color: colors.muted }]}>• {a}</Text>
                      ))}
                    </View>
                  )}

                  {selectedEntry.deliveries.length > 0 && (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>Lieferungen</Text>
                      {selectedEntry.deliveries.map((d, i) => (
                        <Text key={i} style={[styles.detailItem, { color: colors.muted }]}>• {d}</Text>
                      ))}
                    </View>
                  )}

                  {selectedEntry.incidents.length > 0 && (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>Vorkommnisse</Text>
                      {selectedEntry.incidents.map((inc, i) => (
                        <Text key={i} style={[styles.detailItem, { color: colors.muted }]}>• {inc}</Text>
                      ))}
                    </View>
                  )}

                  {selectedEntry.notes ? (
                    <View style={styles.detailBlock}>
                      <Text style={[styles.detailLabel, { color: colors.foreground }]}>Bemerkungen</Text>
                      <Text style={[styles.detailItem, { color: colors.muted }]}>{selectedEntry.notes}</Text>
                    </View>
                  ) : null}
                </>
              )}
            </ScrollView>
            <Pressable
              onPress={() => setSelectedEntry(null)}
              style={({ pressed }) => [styles.closeBtn, { backgroundColor: colors.primary }, pressed && { opacity: 0.8 }]}
            >
              <Text style={styles.closeBtnText}>Schließen</Text>
            </Pressable>
          </View>
        </View>
      </Modal>

      {/* Create Modal */}
      <Modal visible={showCreateModal} transparent animationType="slide">
        <View style={styles.modalOverlay}>
          <ScrollView style={[styles.modalContent, { backgroundColor: colors.surface }]} contentContainerStyle={{ paddingBottom: 40 }}>
            <Text style={[styles.modalTitle, { color: colors.foreground }]}>Neuer Tagebuch-Eintrag</Text>
            <Text style={[styles.modalSubtitle, { color: colors.muted }]}>{formatDate(today)}</Text>

            <View style={styles.formRow}>
              <View style={styles.formHalf}>
                <Text style={[styles.formLabel, { color: colors.muted }]}>Arbeiter</Text>
                <TextInput
                  style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
                  placeholder="Anzahl"
                  placeholderTextColor={colors.muted}
                  value={workers}
                  onChangeText={setWorkers}
                  keyboardType="numeric"
                />
              </View>
              <View style={styles.formHalf}>
                <Text style={[styles.formLabel, { color: colors.muted }]}>Arbeitszeit</Text>
                <View style={styles.timeRow}>
                  <TextInput
                    style={[styles.timeInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
                    value={workFrom}
                    onChangeText={setWorkFrom}
                    placeholder="07:00"
                    placeholderTextColor={colors.muted}
                  />
                  <Text style={[{ color: colors.muted }]}>–</Text>
                  <TextInput
                    style={[styles.timeInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
                    value={workTo}
                    onChangeText={setWorkTo}
                    placeholder="16:00"
                    placeholderTextColor={colors.muted}
                  />
                </View>
              </View>
            </View>

            <Text style={[styles.formLabel, { color: colors.muted }]}>Tätigkeiten (eine pro Zeile)</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder="z.B. Estrich EG verlegt&#10;Elektro OG verkabelt"
              placeholderTextColor={colors.muted}
              value={activities}
              onChangeText={setActivities}
              multiline
              numberOfLines={4}
            />

            <Text style={[styles.formLabel, { color: colors.muted }]}>Lieferungen (eine pro Zeile)</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder="z.B. 5m³ Beton&#10;Fenster Lieferung"
              placeholderTextColor={colors.muted}
              value={deliveries}
              onChangeText={setDeliveries}
              multiline
              numberOfLines={3}
            />

            <Text style={[styles.formLabel, { color: colors.muted }]}>Vorkommnisse</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder="z.B. Wasserrohrbruch Keller"
              placeholderTextColor={colors.muted}
              value={incidents}
              onChangeText={setIncidents}
              multiline
              numberOfLines={2}
            />

            <Text style={[styles.formLabel, { color: colors.muted }]}>Bemerkungen</Text>
            <TextInput
              style={[styles.input, styles.textArea, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]}
              placeholder="Sonstige Anmerkungen..."
              placeholderTextColor={colors.muted}
              value={notes}
              onChangeText={setNotes}
              multiline
              numberOfLines={2}
            />

            <View style={styles.modalButtons}>
              <Pressable
                onPress={() => { setShowCreateModal(false); resetForm(); }}
                style={({ pressed }) => [styles.cancelBtn, { borderColor: colors.border }, pressed && { opacity: 0.7 }]}
              >
                <Text style={[styles.cancelBtnText, { color: colors.muted }]}>Abbrechen</Text>
              </Pressable>
              <Pressable
                onPress={createEntry}
                style={({ pressed }) => [styles.saveBtn, { backgroundColor: colors.primary }, pressed && { opacity: 0.8 }]}
              >
                <Text style={styles.saveBtnText}>Speichern</Text>
              </Pressable>
            </View>
          </ScrollView>
        </View>
      </Modal>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  header: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  backBtn: { padding: 8, marginRight: 8 },
  title: { fontSize: 22, fontWeight: "700", flex: 1 },
  addBtn: { padding: 8 },
  summaryCard: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderRadius: 0, borderWidth: 1, marginBottom: 16 },
  summaryText: { flex: 1 },
  summaryTitle: { fontSize: 16, fontWeight: "600" },
  summarySubtitle: { fontSize: 13, marginTop: 2 },
  list: { paddingBottom: 20 },
  entryCard: { padding: 14, borderRadius: 0, borderWidth: 1, marginBottom: 8 },
  entryHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  dateContainer: { flexDirection: "row", alignItems: "center", gap: 6 },
  entryDate: { fontSize: 15, fontWeight: "600" },
  autoBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 0 },
  autoBadgeText: { fontSize: 11, fontWeight: "600" },
  weatherText: { fontSize: 13, marginTop: 4 },
  entryStats: { flexDirection: "row", gap: 12, marginTop: 8 },
  entryStat: { flexDirection: "row", alignItems: "center", gap: 4 },
  entryStatText: { fontSize: 12 },
  activityPreview: { fontSize: 13, marginTop: 8 },
  emptyState: { alignItems: "center", paddingTop: 60, gap: 12 },
  emptyText: { fontSize: 16, fontWeight: "500" },
  emptySubtext: { fontSize: 13, textAlign: "center", paddingHorizontal: 32 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  modalContent: { borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, maxHeight: "90%" },
  modalTitle: { fontSize: 18, fontWeight: "700" },
  modalSubtitle: { fontSize: 14, marginTop: 4, marginBottom: 16 },
  detailSection: { fontSize: 14, marginTop: 8 },
  detailBlock: { marginTop: 16 },
  detailLabel: { fontSize: 15, fontWeight: "600", marginBottom: 6 },
  detailItem: { fontSize: 14, marginBottom: 3 },
  closeBtn: { paddingVertical: 14, borderRadius: 0, alignItems: "center", marginTop: 16 },
  closeBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  formRow: { flexDirection: "row", gap: 12, marginBottom: 4 },
  formHalf: { flex: 1 },
  formLabel: { fontSize: 13, fontWeight: "500", marginBottom: 6, marginTop: 8 },
  input: { borderWidth: 1, borderRadius: 0, padding: 12, fontSize: 15, marginBottom: 8 },
  textArea: { minHeight: 70, textAlignVertical: "top" },
  timeRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  timeInput: { flex: 1, borderWidth: 1, borderRadius: 0, padding: 10, fontSize: 14, textAlign: "center" },
  modalButtons: { flexDirection: "row", gap: 12, marginTop: 16 },
  cancelBtn: { flex: 1, paddingVertical: 14, borderRadius: 0, borderWidth: 1, alignItems: "center" },
  cancelBtnText: { fontSize: 15, fontWeight: "600" },
  saveBtn: { flex: 1, paddingVertical: 14, borderRadius: 0, alignItems: "center" },
  saveBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
});
