import AsyncStorage from "@react-native-async-storage/async-storage";
import { timelineEngine } from "@/lib/timeline-engine";

const DIARY_KEY = "construction-diary";

export type DiaryEntry = {
  id: string;
  projectId: string;
  date: string; // YYYY-MM-DD
  weather?: {
    temperature: number;
    description: string;
    icon: string;
  };
  workersOnSite?: number;
  workHours?: { from: string; to: string };
  activities: string[];
  incidents: string[];
  deliveries: string[];
  notes: string;
  protocolIds: string[];
  photos: string[];
  createdAt: string;
  updatedAt: string;
  autoGenerated: boolean;
};

export async function getDiaryEntries(projectId?: string): Promise<DiaryEntry[]> {
  try {
    const raw = await AsyncStorage.getItem(DIARY_KEY);
    const entries: DiaryEntry[] = raw ? JSON.parse(raw) : [];
    if (projectId) return entries.filter((e) => e.projectId === projectId);
    return entries.sort((a, b) => b.date.localeCompare(a.date));
  } catch {
    return [];
  }
}

export async function getDiaryEntryForDate(projectId: string, date: string): Promise<DiaryEntry | null> {
  const entries = await getDiaryEntries(projectId);
  return entries.find((e) => e.date === date) || null;
}

export async function saveDiaryEntry(entry: DiaryEntry): Promise<void> {
  const entries = await getDiaryEntries();
  const idx = entries.findIndex((e) => e.id === entry.id);
  const isNew = idx < 0;
  if (idx >= 0) entries[idx] = { ...entry, updatedAt: new Date().toISOString() };
  else entries.push(entry);
  await AsyncStorage.setItem(DIARY_KEY, JSON.stringify(entries));

  // Timeline event for new diary entries
  if (isNew) {
    try {
      await timelineEngine.emit({
        projectId: entry.projectId || "default",
        eventType: "report_generated",
        source: "user",
        title: "Bautagesbericht erstellt",
        description: `Tagebuch ${entry.date}`,
        entityId: entry.id,
        entityType: "report",
        tags: ["diary", "report"],
      });
    } catch {}
  }
}

export async function deleteDiaryEntry(entryId: string): Promise<void> {
  const entries = await getDiaryEntries();
  const filtered = entries.filter((e) => e.id !== entryId);
  await AsyncStorage.setItem(DIARY_KEY, JSON.stringify(filtered));
}

export async function generateDiaryFromProtocols(
  projectId: string,
  date: string,
  protocols: Array<{ id: string; title: string; summary?: string; weather?: any }>
): Promise<DiaryEntry> {
  const existing = await getDiaryEntryForDate(projectId, date);

  const entry: DiaryEntry = existing || {
    id: `diary-${projectId}-${date}`,
    projectId,
    date,
    activities: [],
    incidents: [],
    deliveries: [],
    notes: "",
    protocolIds: [],
    photos: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    autoGenerated: true,
  };

  // Merge protocol data
  entry.protocolIds = [...new Set([...entry.protocolIds, ...protocols.map((p) => p.id)])];
  
  // Auto-fill activities from protocol titles
  const newActivities = protocols
    .map((p) => p.title || p.summary || "")
    .filter((a) => a && !entry.activities.includes(a));
  entry.activities = [...entry.activities, ...newActivities];

  // Use weather from first protocol that has it
  if (!entry.weather) {
    const withWeather = protocols.find((p) => p.weather);
    if (withWeather?.weather) {
      entry.weather = {
        temperature: withWeather.weather.temperature,
        description: withWeather.weather.description,
        icon: withWeather.weather.icon,
      };
    }
  }

  entry.updatedAt = new Date().toISOString();
  await saveDiaryEntry(entry);
  return entry;
}

export function formatDiaryForExport(entry: DiaryEntry): string {
  let text = `BAUTAGEBUCH – ${formatDate(entry.date)}\n`;
  text += "═".repeat(50) + "\n\n";

  if (entry.weather) {
    text += `Wetter: ${entry.weather.description}, ${entry.weather.temperature}°C\n`;
  }
  if (entry.workersOnSite) {
    text += `Arbeiter vor Ort: ${entry.workersOnSite}\n`;
  }
  if (entry.workHours) {
    text += `Arbeitszeit: ${entry.workHours.from} – ${entry.workHours.to}\n`;
  }
  text += "\n";

  if (entry.activities.length > 0) {
    text += "TÄTIGKEITEN:\n";
    entry.activities.forEach((a) => { text += `  • ${a}\n`; });
    text += "\n";
  }

  if (entry.deliveries.length > 0) {
    text += "LIEFERUNGEN:\n";
    entry.deliveries.forEach((d) => { text += `  • ${d}\n`; });
    text += "\n";
  }

  if (entry.incidents.length > 0) {
    text += "VORKOMMNISSE:\n";
    entry.incidents.forEach((i) => { text += `  • ${i}\n`; });
    text += "\n";
  }

  if (entry.notes) {
    text += `BEMERKUNGEN:\n${entry.notes}\n`;
  }

  return text;
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr + "T00:00:00");
  const days = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"];
  const months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"];
  return `${days[d.getDay()]}, ${d.getDate()}. ${months[d.getMonth()]} ${d.getFullYear()}`;
}
